# Generated by Django 4.2.10 on 2024-03-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20, verbose_name='customers name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email customer')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Customers number')),
                ('status', models.CharField(max_length=15, verbose_name='Status customer')),
                ('created_at', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
