# Generated by Django 4.2.10 on 2024-03-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_customersmanagement_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmanagement',
            name='address',
            field=models.CharField(max_length=40, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='customersmanagement',
            name='campaing',
            field=models.CharField(default='Null', max_length=25, null=True, verbose_name='Campaing'),
        ),
        migrations.AlterField(
            model_name='customersmanagement',
            name='notes',
            field=models.TextField(max_length=150, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customersmanagement',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name='Customers number'),
        ),
        migrations.AlterField(
            model_name='customersmanagement',
            name='preference',
            field=models.CharField(max_length=25, null=True, verbose_name='Interaction'),
        ),
    ]
