# Generated by Django 4.2.10 on 2024-03-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='task title')),
                ('description', models.TextField(max_length=50, verbose_name='description')),
                ('priority', models.CharField(choices=[('N', 'NORMAL'), ('M', 'MEDIANA'), ('A', 'ALTA')], default='N', max_length=10)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at', '-title'],
            },
        ),
    ]
