# Generated by Django 4.2.10 on 2024-03-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmanagement',
            name='description',
            field=models.TextField(max_length=150, verbose_name='description'),
        ),
    ]
