# Generated by Django 4.2.10 on 2024-03-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasksmanagement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmanagement',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
