# Generated by Django 4.2.10 on 2024-04-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_alter_customersmanagement_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40, verbose_name='Asunto')),
                ('asigned_to', models.CharField(max_length=30, verbose_name='Asignacion')),
                ('agent', models.CharField(max_length=20, verbose_name='Agente')),
                ('description', models.TextField(max_length=600, verbose_name='Descripcion')),
                ('priority', models.CharField(choices=[('Normal', 'N'), ('Mediana', 'M'), ('Alta', 'A')], max_length=10, verbose_name='Prioridad')),
                ('ticket_type', models.CharField(blank=True, max_length=17, null=True, verbose_name='Tipo')),
                ('chanel', models.CharField(max_length=15, null=True, verbose_name='Canal')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.customersmanagement')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'ordering': ['-subject'],
            },
        ),
    ]
