# Generated by Django 4.2.10 on 2024-04-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='Abierto', max_length=10, verbose_name='Estado'),
        ),
    ]
